export const mockReport = {
  repoUrl: "",
  analyzedAt: null,
  sourceType: "empty",
  detectedProjectType: "",
  analyzedFilesCount: 0,
  currentVersion: "",
  targetVersion: "",
  availableTargetVersions: [],
  database: "",
  readinessScore: null,
  metrics: {
    securityIssues: null,
    complexityHotspots: null,
    manualMigrationWeeks: null,
    codexAssistedWeeks: null,
    maintainabilityGainPercent: null,
  },
  upgradePlan: [],
  securityHotspots: [],
  complexityHotspots: [],
  databaseNotes: [],
  technologies: [],
  databases: [],
  detectedLibraries: [],
  findings: {
    security: [],
    complexity: [],
    pii: [],
    suggestions: [],
  },
  documentationSections: [],
  docsRows: [],
  roadmapSections: [],
  roadmap: {
    summary: "",
  },
  cannotAutomate: [],
  canAccelerate: [],
  sampleAppPreview: {
    title: "",
    summary: "",
  },
};
